### ISSUE TITLE
Selected item is not scrolled to when dropdown is open

### ISSUE THREAD

**Issue by MatejQ** [angular-ui/ui-select#1227]
If dropdown contains more items (so that there is a scrollbar), if currently selected item is below the initial viewport, it is not scrolled to when dropdown is open. It's where ui-select differs from a standard combo-box in functionality.
To reproduce:
1. Open any demo of ui-select that contains more than one viewport of items in the dropdown, such as  [this one](http://embed.plnkr.co/jBJkDb/preview)
2. Select an item that is outside initial viewport - in the plunker above, select "Nicole" from the first ui-select
3. Open the ui-select again - it is still scrolled on the top. If you care not to hover on any of the items, only use the scrollbar to scroll below, you can see Nicole is still highlighted. The highlight is changed when you hover on the items.
I tried to write a directive to fix this but couldn't get my hands on an "on-open" event and even if I could, I don't know if it is possible to make it scroll where necessary.
I also went through all existing issues and was quite surprised no one reported this...

**Comment by Jozef2** [comment]
This also happens when drop down contains many items, the selected one is not in first choices and user expands the drop down (see [Plunker example](http://embed.plnkr.co/e3Y2iyM4tQPO1OdTj87A/preview)). Although the choice is visually selected, user has to manually scroll to it to actually find it, what is annoying for longer list of items.

**Comment by MichalJakubeczy** [comment]
+1

**Comment by MichalJakubeczy** [comment]
This is fixed in latest release (0.13.2)

**Comment by MatejQ** [comment]
OK, then I am closing this issue.

**Comment by lohuon** [comment]
This is actually not fixed. I'm using version 0.17.1 and having the same issue. I'm using the following code, and it scrolls back to the top regardless of which item is selected.

`<div class="form-group">
    <ui-select id="font-picker" reset-search-input="false" append-to-body="true" ng-model="data.selectedFont" on-select="selectNewFont($item, $model)" theme="bootstrap" title="Choose a font" style="width: 200px; z-index:20000">
        <ui-select-match placeholder="Select or search for a font in the list...">{{$select.selected.name}}</ui-select-match>
        <ui-select-choices style="max-height: 350px;" group-by="familyGroupFn" repeat="font in data.fonts | removeAleo | filter: $select.search">
            <div ng-bind-html="font.imgTxt"></div>
            <small ng-bind-html="font.type | highlight: $select.search"></small>
        </ui-select-choices>
    </ui-select>
</div>`

**Comment by ShankzPatil** [comment]
any updates on this issue ??
same happening with me also
