### ISSUE TITLE
weird look of ui-select in bootstrap modal.

### ISSUE THREAD

**Issue by nasr18** [angular-ui/ui-select#1647]
![bootstrapmodal](https://cloud.githubusercontent.com/assets/7514936/15920831/d6c90fdc-2e3a-11e6-9f3b-d2d25573f158.png)

**Comment by user378230** [comment]
I think this is fixed by #1631. 

Please test with the new version when it is released. (Or you can take ui-select from one of the latest plunkrs here: http://angular-ui.github.io/ui-select/#examples)

**Comment by nasr18** [comment]
ok will try and let you know.

**Comment by adaromu** [comment]
I still see this issue. http://codepen.io/adaromu/pen/dXGwVG
OS: win10
Browser: Chrome, Firefox, Edge
Code version: 0.18

**Comment by user378230** [comment]
Assuming fixed...
