### ISSUE TITLE
Cannot create property '_uiSelectChoiceDisabled' on ...

### ISSUE THREAD

**Issue by nehalist** [angular-ui/ui-select#1661]
### Bug description:
```
<ui-select multiple tagging tagging-label="(custom 'new' label)" ng-model="ctrl.multipleDemo.colors" theme="bootstrap" sortable="true" ng-disabled="ctrl.disabled" style="width: 300px;" title="Choose a color">
        <ui-select-match placeholder="Select colors...">{{$item}}</ui-select-match>
        <ui-select-choices repeat="color in availableColors | filter:$select.search">
          {{color}}
        </ui-select-choices>
      </ui-select>
```
Directly copied from the plunker example triggers "Cannot create property '_uiSelectChoiceDisabled' on string 'blue'" (respectively for all other colors in my array).

Additionally: the demo (http://angular-ui.github.io/ui-select/demo-tagging.html) triggers "Cannot read property 'length' of undefined" if you remove the existent tags.

### Link to minimally-working plunker that reproduces the issue:
Works fine in Plunker. I have no idea why.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.4.10

UI-Select: 0.18.0

Bootstrap/Select2/Selectize CSS (if applicable): ~3.3.6

**Comment by peterreisz** [comment]
I have a similar issue:

Update the tagging example version to 0.18.0 and click inside the first ui-select.
The following error shows up in the javascript console for every item:

```
TypeError: Cannot create property '_uiSelectChoiceDisabled' on string 'Green'
    at ctrl.isDisabled (select.js:603)
    at Array.fn1 (eval at <anonymous> (angular.js:14086), <anonymous>:4:1163)
    at expressionInputsWatch (angular.js:15136)
    at Scope.$digest (angular.js:16655)
    at Scope.$apply (angular.js:16928)
    at HTMLInputElement.<anonymous> (angular.js:24551)
    at defaultHandlerWrapper (angular.js:3398)
    at HTMLInputElement.eventHandler (angular.js:3386)
```

plunkr: http://plnkr.co/edit/SsCE6gnNQeSOtBx0lNld?p=preview

Versions:
angular: 1.5.0
ui-select: 0.18.0
bootstrap: 3.1.1

**Comment by rszczypka** [comment]
Reporting the same issue:
Angular 1.5.6
ui-select 0.18.0

**Comment by peterreisz** [comment]
Connected problem: ui-select modifies the data structure of the item, and it can travels back to the server. We have very strict server side validation and unknown properties are not allowed, so upgrading to version v0.18.0 broke several functions of our application.
It would be good to store the additional properties of the item somewhere else.

**Comment by mcantrell** [comment]
also encountered the issue with:

    "angular": "~1.4.12",
    "ui-select": "angular-ui-select#~0.18.0"

downgrading to 0.17.1 fixed the issue.

**Comment by felipsant** [comment]
Same problem here. Thanks mcantrell for the tip.

**Comment by druxax** [comment]
0.17.1 - haven't this problem, but please fix 0.18+

**Comment by that1guy** [comment]
This issue still reproduces with 0.17.1 for me.  See plunker here:

http://plnkr.co/edit/p4AYyEJ8XVmAjvVddx6l?p=preview

**Comment by r-navarro** [comment]
Ui-select loop over object in 0.18.0.

`<ui-select-choices repeat="item in items"`
where items is something like :
`var items=[];`
`..loop ..`
`items.push({key:value})`

Then to have a nice display don't forget to print only the value : 

`<div data-ng-bind-html="item.key | highlight: $select.search"></div>`

Tips to send only the selected value and not the whole JS object you can do something like this : 

`<ui-select-choices`
                   ` repeat="item.key as value in items | filter: $select.search track by $index"`
                    `..others attributes..>`
                `<div data-ng-bind-html="value.key | highlight: $select.search"></div>`
`</ui-select-choices>`

**Comment by NateJBeck** [comment]
Reporting same issue with: `angular 1.4` + `ui-select 0.18.0` 
Downgrading to `0.17.1` did not work for me

Console error occurs when selecting an element from the tag dropdown

**Comment by that1guy** [comment]
I've finally downgraded to `0.16.1` and everything is working as expected.

**Comment by jukkasi** [comment]
+1

Angular 1.5.7 & ui-select 0.18.0

```
<ui-select multiple ng-model="ctrl.form.languages" theme="bootstrap">
    <ui-select-match placeholder="Valitse kielet...">{{'language.' + $item | translate}}</ui-select-match>
    <ui-select-choices repeat="lng in ctrl.availableLanguages">
        <div ng-bind-html="'language.' + lng | translate"></div>
    </ui-select-choices>
</ui-select>
```

**Comment by yobre** [comment]
+1

**Comment by robertocan** [comment]
+1
Angular 1.5.5
ui-select 0.18.0

**Comment by user378230** [comment]
Fixed by #1712

**Comment by nehalist** [comment]
@user378230 bug still exists in `v0.18.1`.

```
<ui-select multiple tagging tagging-label="(custom 'new' label)" ng-model="ctrl.multipleDemo.colors" theme="bootstrap" sortable="true" style="width: 300px;" title="Choose a color">
        <ui-select-match placeholder="Select colors...">{{$item}}</ui-select-match>
        <ui-select-choices repeat="color in ['red', 'blue'] | filter:$select.search">
          {{color}}
        </ui-select-choices>
      </ui-select>
```

Still triggers `Cannot create property '_uiSelectChoiceDisabled' on string 'red` (or any other color).

**Comment by user378230** [comment]
Impossible, the word `_uiSelectChoiceDisabled` doesn't exist in `select.js` any more in [select.js](https://github.com/angular-ui/ui-select/blob/master/dist/select.js) :wink: *(Check for yourself)*

Please test more thoroughly before posting in issues. Thanks! :+1:

**Comment by nehalist** [comment]
Indeed, my bower update went wrong and I still used a previous version. My bad, sorry.

Everything works fine now. Thanks!
