### ISSUE TITLE
Your Example Plunkers seem to be broken

### ISSUE THREAD

**Issue by ivanmcgregor** [angular-ui/ui-select#1828]
### Bug description:

[Your Example Plunkers](http://angular-ui.github.io/ui-select/#examples) seem to be broken. For example is the Plunker with the remote call to the Google maps API does not work. As I wanted to use it, I quickly adapted it: http://plnkr.co/edit/ltWxBQ9TG5RbFIitD74X?p=preview
Feel free to take over the changes to your Plunkers
### Link to minimally-working plunker that reproduces the issue:

Your example plunkers:
- http://angular-ui.github.io/ui-select/demo-basic.html 
- http://angular-ui.github.io/ui-select/demo-append-to-body.html
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.8
UI-Select: 0.19.3
Bootstrap/Select2/Selectize CSS (if applicable): 0.19.3

**Comment by bobisch** [comment]
Yes, that is frustrating.  Probably addressed by PR #1793, but I don't know who has to act on it at this point.

**Comment by Jefiozie** [comment]
It is not addressed by #1793 as this is not merged in the branche. Had a look and in the docs folder are a couple of things different than on the example page. I believe the contributes should have a look at this. @user378230 , @aaronroberson

**Comment by Jefiozie** [comment]
@user378230 can you take a look at the examples? Will this be fixed in next release?

**Comment by Jefiozie** [comment]
There are changes on the examples. Think this problem is resolved. Can you verify?

**Comment by user378230** [comment]
I'll close on next release to ensure docs are correctly deploy when a new version is released.

**Comment by ivanmcgregor** [comment]
The Demo-append-to-body appears to be working, yet the querying for addresses in the demo-basic still does not work

**Comment by user378230** [comment]
@ivanmcgregor Works for me... Try typing something.

**Comment by Jefiozie** [comment]
@ivanmcgregor, working here.

**Comment by ivanmcgregor** [comment]
Well it does for this: 
![image](https://cloud.githubusercontent.com/assets/13334936/20175627/06084772-a744-11e6-98dd-7bb8e80db438.png)

But with the same search term nothing happens here: 
![image](https://cloud.githubusercontent.com/assets/13334936/20175662/2e414dd8-a744-11e6-9124-b246deda2d2d.png)

**Comment by ivanmcgregor** [comment]
Sorry, opened the demo-basic with devtools open and then it worked. Maybe the old files were still in the cache.

**Comment by Jefiozie** [comment]
Great! Can you close the case?

**Comment by Jefiozie** [comment]
@user378230 can you close the case?
