### ISSUE TITLE
multi-select tags with bootstrap theme - value in using btn-primary css styling?

### ISSUE THREAD

**Issue by danfuterman** [angular-ui/ui-select#195]
When using multi-select with the bootstrap theme, it is possible to select (click on) a tag in the list of selected items and highlight this:
![image](https://cloud.githubusercontent.com/assets/1052668/4277847/bd509a72-3d12-11e4-8c8d-19651db2e116.png)

However, when using the select2 theme, there is no visible change when selecting (clicking on) a tag in the list:
![image](https://cloud.githubusercontent.com/assets/1052668/4277875/0ddd48c8-3d13-11e4-97f5-7b4fed851ce7.png)

I'm not sure if there's any value in being able to select/highlight an item in the list, as when using the bootstrap theme, but if it doesn't serve any real purpose, it could be beneficial to remove the btn-primary styling, as well as for the sake of consistency across the bootstrap/select2 themes.

The source of this issue (if it is an issue) appears to be in https://github.com/angular-ui/ui-select/blob/fc42fdfb5c80c86a2d23c373184f5221eca28af0/src/bootstrap/match-multiple.tpl.html

**Comment by dimirc** [comment]
Looks like it was already solved long time ago

**Comment by joelcdoyle** [comment]
I've noticed this too, and I'm looking for a way NOT to add btn-primary class to the item when clicking on it. Is there a way to prevent this?

**Comment by danfuterman** [comment]
Tested with v0.12.0 and the issue still seems to be there, i.e. when using multi-select with the bootstrap theme, it is still possible to select (click on) a tag in the list of selected items and highlight this item.

**Comment by vibhordube** [comment]
This breaks my site's multiselect box as I have overwritten CSS for class .btn-primary. Please fix this. Overriding the whole thing with other CSS rule for now.
