### ISSUE TITLE
Dropdown options are hiding down, if there is no room space. 

### ISSUE THREAD

**Issue by DineshkumarT** [angular-ui/ui-select#234]
![roomspace_issue](https://cloud.githubusercontent.com/assets/8824303/4436940/8ed922b6-4787-11e4-8310-5336d503dae7.JPG)

Normal dropdowns are displaying the options over the debugging tools,but the ui-select dropdown is displaying the options under the debugging tools.

Not able to select the options in this scenario.

**Comment by drewbeck** [comment]
+1 for drop above. Default browser select controls do it, anything that wishes to replace that functionality should also do it!

I'm a ui-select2 user who is aching to be able to switch to ui-select, and this is definitely a requirement.

**Comment by dtomaszewski** [comment]
+1

**Comment by Oceanswave** [comment]
+1

**Comment by Jefiozie** [comment]
I think this is already resolved in a version. Added a screenshot what i have.

![image](https://cloud.githubusercontent.com/assets/17835373/19966656/0c3f0fee-a1cd-11e6-8de1-ccd54cfc2bd4.png)

@user378230 , still a enhancement (maybe i'm missing something here) or can we close it?

**Comment by user378230** [comment]
Not sure, this is a old issue though, so we'll close it. I'm sure someone will shout if they have a problem still.

**Comment by mwpowellhtx** [comment]
This is still an issue, unless I missed a fix for it somewhere along the way. In my case I have a selectmenu within a modal dialog.

![image](https://cloud.githubusercontent.com/assets/1824187/22959823/3cac8afe-f307-11e6-8deb-bf6e6b903315.png)

**Comment by gonza8888** [comment]
I have the same issue, when I want to select, it goes behind my next item.

![image](https://cloud.githubusercontent.com/assets/1005027/23561562/7b895af4-001d-11e7-8a8f-32abb1f211e7.png)

And heres the code:

```
    <div class="list">
		  <div class="item item-divider">
	      Completar los datos para estacionar
	      </div>

		  <div class="item" >
		    <!--<i class="icon ion-mic-a"></i>-->
		    Calle seleccionada
		    <span class="item-note">
		    {{estacionar.calle | json}}
		    </span>
		  </div>

		  <div class="item" >
		    Calle
		    <span class="item-note">
			  <ui-select ng-model="estacionar.calle" theme="selectize" ng-disabled="disabled" style="width: 300px;" title="Calles">
			      <ui-select-match placeholder="Escribir calle...">{{$select.selected.name}}</ui-select-match>
			      <ui-select-choices repeat="calle in calles | filter: $select.search">
			          <span ng-bind-html="calle.name | highlight: $select.search"></span>
			          <small ng-bind-html="calle.id | highlight: $select.search"></small>
			      </ui-select-choices>
			  </ui-select>
		    </span>
		  </div>		
</div>

```
