### ISSUE TITLE
"Track by" does not work on multiple ui-select with objects

### ISSUE THREAD

**Issue by artkoenig** [angular-ui/ui-select#665]
Here the example:
http://plnkr.co/edit/3KLlmX19Qx6meOk52Jyn?p=preview

Using `track by` in "Array of objects" example has no effect, angular generates `$$hashKey` fields for selected objects.

**Comment by abobwhite** [comment]
I am also seeing this issue. It's become very problematic.

**Comment by abobwhite** [comment]
It's hard to look back to the old files because the code was recently split into new files.

**Comment by yoyoprs** [comment]
+1 :(

**Comment by nashant** [comment]
Is there going to be a fix for this some time soon? At the moment I'm having to resort to using angular.extend() to add the $$hashKey

**Comment by thefewminutes** [comment]
+1

**Comment by estvmachine** [comment]
Exist a partial solution for this problem??

**Comment by evillemez** [comment]
Yeah, this one kinda hurts... track by usually helps with performance, and I have a huge list of objects (languages) in a multiselect.

**Comment by catchshyam** [comment]
+1

**Comment by williamoliveira** [comment]
+1

**Comment by arseneoaa** [comment]
+1

**Comment by nadavsinai** [comment]
+1

**Comment by NetanelBasal** [comment]
+1

**Comment by morozovm** [comment]
+1

**Comment by logannc** [comment]
+1

**Comment by sidoruk-sv** [comment]
+1

**Comment by nadavivry** [comment]
+1

**Comment by n3wtn9** [comment]
+1

**Comment by noxan** [comment]
+1

**Comment by acabra85** [comment]
+1

**Comment by loose11** [comment]
I hope my fix helps

**Comment by acabra85** [comment]
I have seen the pull request, https://github.com/angular-ui/ui-select/pull/1383, it says the CI tests failed. Thanks for your posting

**Comment by loose11** [comment]
The pull request fails because of the old build workflow. Other pull requests have the same issue.

**Comment by estvmachine** [comment]
:( good try!

**Comment by giacomolm** [comment]
+1
I created a filter as a workaround, but I would prefer to use 'track by' - mainly for performance issue (I didn't understand when the filters are called). Does it work the from the latest commit?

**Comment by artuska** [comment]
+1

**Comment by aaronroberson** [comment]
@artuska This should be fixed in the latest version. Please see https://github.com/angular-ui/ui-select/commit/6c52e412e8be48f2831b95e7ab930bbf483f7c82 and confirm or deny.

**Comment by ivelfan** [comment]
Still occured in v0.16.1.

`<ui-select-choices repeat="purposeOfVisit in purposeOfVisits | filter: {name: $select.search} track by purposeOfVisit.id">` doesn't delete $$hashkey in object.

**Comment by DriesVandermeulen** [comment]
Also on 0.17.1 still occurring.

**Comment by dunwho** [comment]
The first response here provided a solution for me. It seems that simply including "multiple" as an attribute rather than " multiple='true' " causes validation errors within select.js. 

Also, if you track by $index with the above change it seems to work fine. 

[](https://www.bountysource.com/issues/5738626-ngrepeat-dupes-duplicates-in-repeater-are-not-allowed-broken-after-angular-ui-select-upgrade)

> I've spent some time digging into this. I've been able to get past the ngRepeat:dupes by making the following changes:

```
<ui-select multiple='true' ng-model='user.roles' theme='bootstrap'>
  <ui-select-match placeholder='Select a role...'> {{$item}} </ui-select-match>
  <ui-select-choices repeat='role in roles track by $index'> {{role}} </ui-select-choices>
</ui-select>
```

> The big change here was from the simple attribute, multiple to multiple="true". The logic for determining if multiple is in play seems wrong (despite being woefully hard to read...sorry)?

**Comment by DriesVandermeulen** [comment]
Just gave it a test and this does indeed solve this issue...

**Comment by user378230** [comment]
The line 
```js
$select.multiple = (angular.isDefined(attrs.multiple)) ? (attrs.multiple === '') ? true : (attrs.multiple.toLowerCase() === 'true') : false;
```
Doesn't exist.
```
$select.multiple = true
``` 
[Is set in the `uiSelectMultiple` directive itself.](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectMultipleDirective.js#L83)

**Comment by laurenmacam** [comment]
+1

**Comment by agupta-q4** [comment]
:+1: for me, I have two ui-select in my view. very strange that for one instance its working fine, but for its sibling ui-select, it is not. any fixes ?

**Comment by apodznoev** [comment]
@agupta-q4 Thank you man for a code! It didn't resolved the issue with a hash key but fixed my problem with filtering using track by =)

**Comment by iMomen** [comment]
+1
