### ISSUE TITLE
Bootstrap theme doesn't cut off text past border

### ISSUE THREAD

**Issue by lin1412** [angular-ui/ui-select#689]
Hello, I'm using the ui-select with the bootstrap theme, but when I select an option that has an text past the input box size, the text doesn't cut off like the one in select2 theme.

![cutoff](https://cloud.githubusercontent.com/assets/6702898/6271011/e4009d86-b82b-11e4-8b4d-9fc4845aba98.PNG)

**Comment by quietcodes** [comment]
Here's how I fixed the issue
`.ui-select-bootstrap .ui-select-match-text > span {
    display: block;
    text-overflow: ellipsis;
    overflow: hidden;
}`

**Comment by lin1412** [comment]
thanks for the fix. 
This does solve the problem, but it also increases the select box's height when something is selected. To counter this, I had to set the height of .btn-select-white, which causes the location of the dropdown caret to be out of place. Tried changing the caret's margin-top, but a pristine select box and a selected select box have the caret at different locations.

If there another way where it doesn't change the input box's size, or another fix so the caret don't change location. 

Thanks

**Comment by quietcodes** [comment]
I think my instance is inheriting a  `white-space: nowrap` from somewhere. If you add that in, the text should keep to one line.

**Comment by btm1** [comment]
this is how i fixed it:

.ui-select-toggle {
  &.btn {
	padding-right: 23px;
  }
}

**Comment by istibekesi** [comment]
Fix is not working for me:
http://plnkr.co/edit/7vHdHfhwZkw4x5lR6wTl?p=preview
![capture](https://cloud.githubusercontent.com/assets/5990010/6982054/7a50d966-da0c-11e4-93a0-3ee4455d5314.PNG)

Any idea why?

**Comment by exaptis** [comment]
I had the same problem as the pull-left on the ui-select-match-text element will cancel text-overflow. You can try:  
```
.ui-select-match-text  {
  &.pull-left {
    float: none !important;
  }

  > span { 
     display: block; 
     text-overflow: ellipsis; 
     overflow: hidden; 
   }
}
```

**Comment by istibekesi** [comment]
Can you please, fork my plunk and fix it?

**Comment by exaptis** [comment]
You'll find the css adjustment at the end of style.css

http://plnkr.co/edit/Qmxx7CHf3crnXxc8QXCk?p=preview

**Comment by istibekesi** [comment]
Thanks, now it works fine!

**Comment by gerardp** [comment]
@exaptis 
Your fix has a problem with the allow-clear option

![captura de pantalla 2015-05-08 a las 13 48 25](https://cloud.githubusercontent.com/assets/168353/7535853/f022bf4a-f589-11e4-848b-fd9e9b485c29.png)

**Comment by exaptis** [comment]
@gerardp i found a quick-fix, but the solution is not pretty. ui-select does not provide a dedicated class for the clear icon :-(

http://plnkr.co/edit/Qmxx7CHf3crnXxc8QXCk?p=preview

```css
  .ui-select-toggle > a.btn-link  {
    top: 6px;
    position: absolute;
    right: 20px;
  }

  .ui-select-match-text {
    margin-right: 35px;
  }
```

**Comment by gerardp** [comment]
@exaptis 
It works, thanks !!

**Comment by exaptis** [comment]
@lin1412 should this issue really be closed without pull-request? Because it is a bug in the stylesheet, therefore it should only be closed after the bug fix was merged. If you re-open this issue I'll provide a pull-request to fix it.

**Comment by jsudarman** [comment]
hi, I am still having issue on this

-- html file
<div class="col-md-4 osborn-col-pad-sm">
                                                <div class="osborn-small-dropdown"  ng-class="{ 'has-error': submitted && benchmark.futuresBenchmark.$error }">
                                                    <ui-select ng-model="benchmark.futuresBenchmark.selected" theme="bootstrap" class="form-control form-control-dropdown osborn-text-smaller"
                                                               on-select="selectFuturesBenchmark($item, benchmark)">
                                                        <ui-select-match placeholder="Futures new basket is just a dummy dummy dummy dummy dummy test">{{$select.selected.Name}} (Id: {{$select.selected.Id}})</ui-select-match>
                                                        <ui-select-choices group-by="'group'" repeat="item in futuresBenchmarks | benchmarkFilter: $select.search">
                                                            <span ng-bind-html="item.Name | highlight: $select.search"></span>
                                                            <span class="text-muted">(id: <small ng-bind-html="item.Id.toString() | highlight: $select.search"></small>)</span>
                                                        </ui-select-choices>
                                                    </ui-select>
                                                    <span class="text-danger" ng-show="isThisFuturesBasketUsedMoreThanOnce(benchmark)">Basket already in use.</span>
                                                </div>
                                            </div>

-- css file
.ui-select-bootstrap .ui-select-match-text > span { display: block !important; text-overflow: ellipsis!important; overflow: hidden!important; white-space: nowrap!important;}

**Comment by exaptis** [comment]
@jsudarman please provide a plnkr sample.

**Comment by jsudarman** [comment]
http://plnkr.co/edit/NAkPOpGK7aqmgpZ8rrPE?p=preview

**Comment by APelekh** [comment]
@exaptis 
```css
.ui-select-match-text  {
  &.pull-left {
    float: none !important;
  }

  > span { 
     display: block; 
     text-overflow: ellipsis; 
     overflow: hidden; 
   }
}
```
didn't work for me too, but

```css
.ui-select-toggle > a.btn-link  {
    top: 6px;
    position: absolute;
    right: 20px;
  }

  .ui-select-match-text {
    margin-right: 35px;
  }
```
actually worked. Can you help on that?
