### ISSUE TITLE
Can't select with mouse when hostname is "localhost"

### ISSUE THREAD

**Issue by anik786** [angular-ui/ui-select#714]
When I am running the demos normally under my file system everything works okay. However, when I am running the same demos under my localhost:8080, then for some reason you cannot click on the select boxes (although keyboard shortcuts work)! 

However It works fine on 127.0.0.1, but just NOT on localhost:8080. What's even funnier is that this works on Firefox and Chromium just fine regardless if it's on localhost or not! 

Pretty much the exact same problem happened before according to this:
https://github.com/angular-ui/ui-select/issues/666

However that is now closed as he claimed the issue was fixed after updating the select version to 0.9.7. I tried using this version, as well the latest version on Github and the latest version on Bower yet the problem still remains.

Now before people start saying it is a CROS issue, note i'm not loading ANY external URL's. No external CSS, JS, or JSON data. Everything should be working locally. And no errors on the console either, or 404 errors in the resource/ network tab.

I am using:
- Angular version 1.3.14 for both Angular & angular-sanitize, but also tried 1.2.18, which was what the plunker demo was in.
- Google Chrome 40.0.2214.115 (Official Build) 
- OS: Ubuntu 14.04.2 LTS
- Acer Aspire V5-571P (Touchscreen + Keyboard)

Please help me urgently!

**Comment by britvik** [comment]
Same thing is happening to me (selecting an item on localhost doesn't work, but works on 127.0.0.1).

ui-select 0.10.0
angular 1.3.13
chrome 41.0.2272.76 m

Tried downgrading to 0.9.7 as https://github.com/angular-ui/ui-select/issues/666 suggested, but that didn't work either.

**Comment by albertoclarit** [comment]
I also have this problem on ui-select 0.10.0

**Comment by albertoclarit** [comment]
It appears this issue might be chrome related
It is now solved in Chrome Version 41.0.2272.76 (64-bit) 
OS: Yosemite

**Comment by toymachiner62** [comment]
I'm on Chrome Version 41.0.2272.76 (64-bit) and Yosemite and I still have the same issue. Seems to work just fine on Firefox though.

**Comment by ilanthendral** [comment]
This is still an issue in  Chrome Version 42.0.2311.90.

**Comment by fredericbonifas** [comment]
Did you look at issue #546 ? I.e. disabling Batarang extension.

**Comment by alexborisov** [comment]
I can confirm this issue. We discovered this bug occurs only with Chrome on Windows and if running off localhost. My imagination draws a blank as to the possible explanation though.

**Comment by candidosales** [comment]
Thank you!

I have disabled the Batarang and it worked!

**Comment by victordelacruz** [comment]
Same situation here on OSX with Chrome using localhost.

**Comment by cbelhaffef** [comment]
i have a same problem, with ChromeCanary, it's not working, but with Chrome it's working.

**Comment by wesleycho** [comment]
Closing as this appears to not be a library problem.
