### ISSUE TITLE
tagging issue with angular version > 1.2.18

### ISSUE THREAD

**Issue by thlgrant** [angular-ui/ui-select#964]
tagging works as expected (first multiple select) Angular 1.2.18:
![tagworks](https://cloud.githubusercontent.com/assets/5322574/7824742/60309eac-03fd-11e5-883a-590149257e68.PNG)
tagworks

tagging does not work as expected (first multiple select) Angular 1.3.15
![tagbroken](https://cloud.githubusercontent.com/assets/5322574/7824747/686369ba-03fd-11e5-85ea-d7df1b9aeba7.PNG)
tagbroken

Using an angular version greater than 1.2.18 breaks the tagging functionality

**Comment by brianfeister** [comment]
This *might* be fixed with one of the PRs from the [v0.12.0](https://github.com/angular-ui/ui-select/releases/tag/v0.12.0) release that went out yesterday

**Comment by zieemer** [comment]
Unfortunately not problem is still there
please see here http://plnkr.co/edit/hFxGahJEFIggsL2Wdsli?p=preview

**Comment by jjchiw** [comment]
Hi

In version v0.12.0 the tagging without multiple it doesn't work with angular 1.3.0 but it works with v0.11.2

It was in this [merge](https://github.com/angular-ui/ui-select/commit/bb3bfdf252d23e62e181216dc529966d67901eb0#diff-abde4a481e0d1eb6531858ade35f95abR381) 

it changed from `if(ctrl.open && ctrl.activeIndex >= 0){` to `if(ctrl.open && (ctrl.tagging.isActivated || ctrl.activeIndex >= 0)){`

But anyway I'm using angular 1.3.15 and it's not working neither v0.12.0 nor v0.11.2

It seems that between 1.3.0 and 1.3.15 the way the attributes are managed are different.... 

if I have this markup

```html
<ui-select tagging="tagTransform" tagging-tokens ng-model="person.selected" theme="bootstrap" ng-disabled="disabled" style="width: 800px;" title="Choose a person">
```

The default values of tagging-tokens are set here [line](https://github.com/angular-ui/ui-select/blob/2d1422d109dc1cd64213271e59506b14f74d356f/src/uiSelectDirective.js#L112)
```
var tokens = attrs.taggingTokens !== undefined ? attrs.taggingTokens.split('|') : [',','ENTER'];
```

`attrs.taggingTokens` it's not `undefined` its `empty`, so, just changing the line like this 
```
var tokens =(attrs.taggingTokens !== undefined && attrs.taggingTokens !== "") ? attrs.taggingTokens.split('|') : [',','ENTER'];
``` 
the tagging-tokens are set to the default values

Anyway. Since I'm using v0.11.2 with angular v1.3.15 just declaring the tagging tokens in the markup it works.....

```html
<ui-select tagging="tagTransform" tagging-tokens="ENTER" ng-model="person.selected" theme="bootstrap" ng-disabled="disabled" style="width: 800px;" title="Choose a person">
```

Hope this helps....

**Comment by thlgrant** [comment]
Thanks for your replies,

I eventually had success with explicitly declaring the tagging label in v0.12.0
```html
<ui-select tagging tagging-label="(new list)" multiple ng-model="selected.groups" theme="select2">
````

I hope this helps anyone else with the same issues

**Comment by user378230** [comment]
Closing as resolved. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
